#!/bin/bash
#SBATCH -J radixSort           # job name
#SBATCH -o radixSort.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 68              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 02:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=hmayani@cs.stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
icpc proRS.cpp -o 2b_rs -std=c++11
#./2b_rs 10 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-PA-in.txt
#./2b_rs 6 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-TX-in.txt
#./2b_rs 5 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/roadNet-CA-in.txt
#./2b_rs 7 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/ca-AstroPh-in.txt
#./2b_rs 8 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/com-dblp-in.txt
#./2b_rs 9 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/com-lj-in.txt
./2b_rs 4 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/com-orkut-in.txt
./2b_rs 3 0 64 < /work/01905/rezaul/CSE613/HW2/turn-in/com-friendster-in.txt
