#!/bin/bash
#SBATCH -J myMPI           # job name
#SBATCH -o myMPI.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 68              # total number of mpi tasks requested
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 02:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=hmayani@cs.stonybrook.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

./2b_bs 4 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/com-orkut-in.txt
./2b_bs 3 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/com-friendster-in.txt

#./2b_bs 5 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/roadNet-CA-in.txt
#./2b_bs 6 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/roadNet-TX-in.txt
#./2b_bs 7 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/ca-AstroPh-in.txt
#./2b_bs 8 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/com-dblp-in.txt
#./2b_bs 9 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/com-lj-in.txt
#./2b_bs 10 1 64 </work/01905/rezaul/CSE613/HW2/turn-in/roadNet-PA-in.txt
